---
title: "Border heterogeneity"
author: "Martin Kosík"
date: "1 května 2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(data.table)
library(tidyverse)
library(here)
library(sf)
Sys.setlocale("LC_CTYPE", "russian") 
library(mapview)
#library(leaflet)
library(mapedit)
```

```{r}

selected_vars <- c("person_id", "nation", "arest_date", "process_date","live_place", 
                   "birth_place", "birth_year",  "surname", "name", "patronimic", "memory_book")

memorial_lists <- fread("memo_list/memorial_lists.tsv", encoding="UTF-8", sep="\t", 
                        select = selected_vars, quote="", na.strings = "None")



load(here::here("data/eventsClean_v1.RData"))

events <- events %>% 
  dplyr::select(YEAR_STATUTE, YEAR, DATE, ORIGIN_LONG, ORIGIN_LAT, NAME, BIRTH_DATE, SOURCE)

events <- events %>% 
  mutate(names_split = str_split(NAME, pattern = " "),
         first_name = as.factor(map_chr(names_split, nth, 2)),
         surname = as.factor(map_chr(names_split, 1)),
         patronymic = as.factor(map_chr(names_split, nth, 3)),
         number_of_names = as.factor(map_int(names_split, length))) %>% 
  dplyr::select(-c(names_split, NAME))

saveRDS(events, file = here::here("data/eventsClean_v2.RData"))

events <- readRDS(here::here("data/eventsClean_v2.RData"))

events <- events %>% 
  mutate(BIRTH_DATE = as.numeric(BIRTH_DATE))


events_distinct <- events %>% 
  distinct(surname, first_name, BIRTH_DATE, patronymic, SOURCE, ORIGIN_LONG, ORIGIN_LAT)

merged <- memorial_lists %>% 
  left_join(events_distinct, by = c("surname", "name" = "first_name", "birth_year" = "BIRTH_DATE",
                           "patronimic" = "patronymic", "memory_book" = "SOURCE"))


merged <- merged %>% 
  dplyr::select(person_id, ORIGIN_LONG, ORIGIN_LAT) %>% 
  filter(!is.na(ORIGIN_LONG), !is.na(ORIGIN_LAT))

rm(list = c("events", "events_distinct", "memorial_lists"))
gc()

multiple_matches <- merged %>% 
  count(person_id, sort = T) %>% 
  filter(n > 1)

merged <- merged %>% 
  anti_join(multiple_matches, by = "person_id")

rm(multiple_matches)
```


```{r}
ussr_map <- st_read(here::here("data/ussr_shapefiles/1897RussianEmpire.shp"))

ussr_map <- st_read(here::here("data/ussr_shapefiles/1926SovietUnion.shp"))

st_crs(ussr_map) <- "+proj=longlat +datum=WGS84 +no_defs"

ussr_borders <-  ussr_map %>% 
    #group_by(COUNTYFP) %>% 
    summarise(geometry = st_union(.))

ussr_borders <-  ussr_map %>% 
    #group_by(COUNTYFP) %>% 
    summarise(geometry = st_union(.)) %>% 
  st_boundary()



# border_provinces <- c("Karelian ASSR", "Murmansk province", "Leningrad province", "Pskov province", 
#                         "Belorussian ASSR", "Ukrainian ASSR", "Transcaucasian SFSR")



ussr_map <- ussr_map %>% 
  dplyr::select(Id, NameENG, NameRUS)


ggplot(ussr_map) +
    geom_sf(fill = "gray95", color = "gray50", size = 0.5) +
    geom_sf(aes(fill = border_province))+
    theme_void() +
    coord_sf(crs = "+proj=longlat +datum=WGS84 +no_defs", ndiscr = F) + 
    labs(fill = "Border province (in Europe)") + 
    theme(legend.position="bottom")

ggsave(here::here("plots/final/border_provinces_map.pdf"))


mapview(ussr_borders)

mapview(ussr_map)
editMap(mapview(ussr_map))

drawed_polygons <- editMap(mapview(ussr_borders))


saveRDS(drawed_polygons, file = here::here("data/drawed_polygons.RData"))

drawed_polygons <- readRDS(here::here("data/drawed_polygons.RData"))


mapview(drawed_polygons$drawn)



#ussr_borders_lines <- st_cast(ussr_borders, to =  "MULTILINESTRING")

border_lines <- st_intersection(ussr_borders, drawed_polygons$drawn)

mapview(border_lines %>% 
          st)

border_lines %>% 
  st_transform(crs = 7801) %>% 
  st_buffer(dist = 250000, nQuadSegs = 1) %>% 
  st_intersection(ussr_map %>% st_transform(crs = 7801)) %>% 
  mapview()
  

buffer_250km <- border_lines %>% 
  st_transform(crs = 7801) %>% 
  st_buffer(dist = 250000, nQuadSegs = 1) %>% 
  st_intersection(ussr_map %>% st_transform(crs = 7801)) %>% 
  st_transform(crs = "+proj=longlat +datum=WGS84 +no_defs")



ggplot(ussr_map) +
    geom_sf(fill = "gray95", color = "gray50", size = 0.5) +
    geom_sf(data = st_transform(buffer_250km, crs = "+proj=longlat +datum=WGS84 +no_defs"), fill = "gray50")+
    theme_void() +
    coord_sf(crs = "+proj=longlat +datum=WGS84 +no_defs", ndiscr = F) + 
    labs(fill = "Border province (in Europe)") + 
    theme(legend.position="bottom")

ggsave(here::here("plots/final/border_buffer_map.pdf"))



arrests_sf <- st_as_sf(merged, coords = c("ORIGIN_LONG", "ORIGIN_LAT"), crs = 4326) 

arrests_sf <- arrests_sf 

#distances_from_border <- st_distance(arrests_sf, border_lines)

joined <-  arrests_sf %>%
  st_join(buffer_250km, suffix = c("", "_buffer")) %>% 
   st_join(ussr_map, suffix = c("", "_whole")) 


outside_ussr <- joined %>% 
  st_set_geometry(NULL) %>% 
  filter(is.na(border_province))


joined_df <- joined %>% 
  st_set_geometry(NULL) %>% 
  mutate(location = case_when(!is.na(NameENG) ~ "within 250 km border buffer", 
                              !is.na(NameENG_whole) ~ "outside 250 km border buffer",
                              TRUE ~ "outside USSR"))


joined_df %>% 
  count(location)
  
joined_df <- joined_df %>% 
  dplyr::select(person_id, location)

fwrite(joined_df, here::here("data/border_arrests.csv"))

```

