---
title: "Charges"
author: "Martin Kosík"
date: "17 února 2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(data.table)
library(stringi)
```

```{r}
load(here("data/eventsClean_v1.RData"))
```

```{r}
names(events)
events %>% 
  count(SENTENCE_AMNESTY)
```

```{r}
events <- events %>% 
  mutate(n_of_eth_gr = rowSums(.[37:54]), 
         n_of_charges = rowSums(.[26:32]))

events %>% 
  count(n_of_charges, sort = T)

events <- events %>% 
  filter(n_of_eth_gr <= 1)


```


```{r}
minorities_var_names <- names(events) %>% 
  str_subset("ETHNIC_")

charge_var_names <- names(events) %>% 
  str_subset("CHARGE_")



events <- as.data.table(events)

events_eth_long <- melt(events, id.vars = "AID",
                measure.vars = minorities_var_names, 
                variable.name = "ethnicity")[
                  value == 1][,ethnicity := str_remove(ethnicity, "ETHNIC_")][,
                    ethnicity :=  case_when(ethnicity == "BEL" ~ "Belarussian",
                                            ethnicity == "RUS" ~ "Russian",
                               ethnicity == "GER" ~ "German",
                               ethnicity == "POL" ~ "Polish",
                               ethnicity == "UKR" ~ "Ukrainian",
                               TRUE ~ ethnicity) %>% 
                      str_to_title()][, value := NULL]

events_charge_long <- melt(events, id.vars = "AID",
                measure.vars = charge_var_names, 
                variable.name = "charge")[
                  value == 1][,charge := str_remove(charge, "CHARGE_") %>% str_to_title()][
                                                            , value := NULL]

events <- events %>% 
  dplyr::select(AID, YEAR, MONTH, DAY, n_of_eth_gr, SOURCE)

events <- events %>% 
  #left_join(events_charge_long, "AID") %>% 
  left_join(events_eth_long, "AID")

events %>% 
  filter(ethnicity == "German") %>% 
  count(SOURCE_latin, sort = T) %>% 
  View()

events %>% 
  filter(is.na(ethnicity)) %>% 
  count(SOURCE_latin, sort = T) %>% 
  View()

events %>% 
  group_by(SOURCE_latin) %>% 
  summarise(n_missing = sum(is.na(ethnicity)), n_total = n(), 
            n_russian = sum(ethnicity == "Russian", na.rm = T)) %>% 
  mutate(prop_missing = n_missing/n_total) %>%
  arrange(desc(n_total)) %>% 
  View()
  


events$SOURCE_latin <- stri_trans_general(events$SOURCE, "cyrillic-latin")


rm(list = c("events_eth_long", "events_charge_long"))
gc()

charges_by_year <- 
  events %>% 
  filter(!is.na(YEAR), !is.na(charge)) %>% 
  count(YEAR, charge) %>% 
  complete(YEAR, charge, fill = list(n = 0))

charges_by_year %>% 
  mutate(log_n = log(1 + n)) %>% 
  ggplot(aes(x = YEAR, y = n)) + geom_line() + facet_wrap(~charge, scales = "free_y") + theme_bw()

```


```{r}
charges_by_ethn_year <- 
  events %>% 
  filter(!is.na(YEAR), !is.na(charge), !is.na(ethnicity)) %>% 
  count(YEAR, ethnicity, charge) %>% 
  complete(YEAR, ethnicity, charge, fill = list(n = 0))

charges_by_ethn_year %>% 
  filter(charge == "Kulak") %>% 
  mutate(log_n = log(1 + n)) %>% 
  ggplot(aes(x = YEAR, y = log_n)) + geom_line() + facet_wrap(~ethnicity, scales = "free_y") + theme_bw()


```

