---
title: "Data import"
author: "Martin Kosík"
date: "18 března 2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(data.table)
library(tidyverse)
library(readxl)
library(here)
library(lubridate)
library(klaR)
library(caret)
library(pryr)
library(bnlearn)
library(bnclassify)
Sys.setlocale("LC_CTYPE", "russian") 
library(naniar)
library(knitr)
library(kableExtra)
```

```{r}
memorial_lists %>% 
  #filter()
  count(memory_book_url, sort = T)
memorial_lists %>% 
  filter(surname == "None") %>% 
  View()

```
missing arrest date: 1 650 941
non-missing arrest date: 1 053 658
missing arrest date but non-missing process date: 903506
```{r}
memorial_lists <- fread("memo_list/memorial_lists.tsv", encoding="UTF-8", nrows = 20, sep="\t")
names(memorial_lists)
selected_vars <- c("person_id", "nation", "surname", "name", "previous_repression",
                   "next_repression", "rehabilitation_reason", "memory_book", "memory_book_url")
selected_vars <- c("person_id", "nation", "arest_date", "process_date", "surname", "name")
memorial_lists <- fread("memo_list/memorial_lists.tsv", encoding="UTF-8", sep="\t", 
                        select = selected_vars, quote="", na.strings = "None")
memorial_lists <- fread("memo_list/memorial_lists.tsv", encoding="UTF-8", sep="\t", 
                        select = selected_vars, quote="")

memorial_lists <- memorial_lists[surname != "None",]

memorial_lists <- memorial_lists[, place_missing := ifelse(birth_place == "None" & live_place == "None", 1, 0)]


memorial_lists <- memorial_lists[, no_date := ifelse(process_date == "None" & arest_date == "None", 1, 0)]
memorial_lists <- memorial_lists[, nation_latin := stri_trans_general(nation, "cyrillic-latin")]
memorial_lists <- memorial_lists[, no_ethnicity := ifelse(nation == "None", 1, 0)]
memorial_lists <- memorial_lists[, no_date_of_arrest := ifelse(arest_date == "None", 1, 0)]
memorial_lists <- memorial_lists[, no_date_of_process := ifelse(process_date == "None", 1, 0)]


translations <- read_excel(here::here("data/ethnicity_translations.xlsx"))

opts_current$set(label = "missingness_of_ethnicity_and_date")
memorial_lists %>% 
  count(no_date, no_ethnicity) %>% 
  mutate(no_date = recode_factor(no_date, `1` = "Missing",  `0` = "Present"),
         no_ethnicity = recode_factor(no_ethnicity, `1` = "Missing", `0` = "Present")) %>% 
  spread(key = no_date, value = n) %>% 
    kable("latex", booktabs = T, caption = "Missingness of Ethnicity and Dates of Arrest and Process",
          linesep = "",
        col.names = c("Ethnicity", "Missing", "Present"), format.args = list(big.mark = " ")) %>% 
  add_header_above(c(" " = 1, "Date of Arrest or Process" = 3)) %>% 
  #kable_styling(font_size = 8) %>% 
  write_file("tables/missingness_of_ethnicity_and_date.tex")

opts_current$set(label = "missing_date_of_arrest_process")
memorial_lists %>% 
  count(no_date_of_arrest, no_date_of_process) %>% 
  mutate(no_date_of_arrest = recode_factor(no_date_of_arrest, `1` = "Missing",  `0` = "Present"),
         no_date_of_process = recode_factor(no_date_of_process, `1` = "Missing", `0` = "Present")) %>% 
  spread(key = no_date_of_arrest, value = n) %>% 
  kable("latex", booktabs = T, caption = "Missing Dates of Arrest and Process", linesep = "",
        col.names = c("Date of Process", "Missing", "Present"), format.args = list(big.mark = " ")) %>% 
  add_header_above(c(" " = 1, "Date of Arrest" = 3)) %>% 
  #kable_styling(font_size = 8) %>% 
  write_file("tables/missing_date_of_arrest_process.tex")


memorial_lists_nas <- replace_with_na_all(memorial_lists,
                    condition = ~.x == "None")


```


```{r}
n_of_obs <- nrow(memorial_lists)

opts_current$set(label = "missing_data_count")
memorial_lists %>% 
  dplyr::select(nation, arest_date, process_date, name) %>% 
  summarise_all(funs(sum(. == "None"))) %>% 
  gather(key = "Variable", value = "missing_count") %>% 
  mutate(missing_pct = missing_count/n_of_obs * 100,
         Variable = recode_factor(Variable, "nation" = "Ethnicity","arest_date" = "Date of Arrest", 
                       "process_date" =  "Date of Process", "name" = "First Name", "surname" = "Surname")) %>% 
  kable("latex", booktabs = T, caption = "Missing Data by Variable", linesep = "",
        col.names = c("Variable", "Number of Missing Obs.", "Percent of Missing Obs."),
        format.args = list(big.mark = " ")) %>% 
 # kable_styling(font_size = 8) %>% 
  write_file("tables/missing_data_count.tex")
```



```{r}
memorial_lists <-
  memorial_lists %>% 
  left_join(translations, by = "nation") %>% 
  mutate(ethnicity = ifelse(is.na(ethnicity), "Other", ethnicity))

memorial_lists <- memorial_lists %>% 
  separate(arest_date, sep = "\\.", into = c("DAY", "MONTH", "YEAR"), remove = FALSE) %>% 
  separate(process_date, sep = "\\.", into = c("DAY_PROCESS", "MONTH_PROCESS", "YEAR_PROCESS"), remove = FALSE) %>%
  mutate_at(vars("DAY", "MONTH", "YEAR", "DAY_PROCESS", "MONTH_PROCESS", "YEAR_PROCESS"),
             funs(as.numeric(ifelse(. %in% c("None", "_"), NA, .))))

```

```{r}
memorial_lists %>% 
  filter(!is.na(YEAR), !is.na(YEAR_PROCESS)) %>% 
  filter(YEAR == YEAR_PROCESS) %>% 
  count()
  
```


```{r}
memorial_lists %>% 
  count(YEAR, ethnicity) %>% 
  filter(YEAR < 1960, YEAR > 1920) %>% 
  mutate(log_n = log(nn + 1)) %>% 
  ggplot(aes(x = YEAR, y = log_n)) + geom_line() + facet_wrap(~ ethnicity) + theme_bw()

memorial_lists %>% 
  count(YEAR, ethnicity) %>% 
  filter(YEAR < 1960, YEAR > 1920) %>% 
  ggplot(aes(x = YEAR, y = nn)) + geom_line() + facet_wrap(~ ethnicity) + theme_bw() +
  scale_y_log10()

```


```{r}
levels(data_labeled$patronimic) %>% 
  View()
```


# New naive bayes

```{r}
selected_vars <- c("person_id", "nation", "surname", "name", "patronimic")


memorial_lists <- fread("memo_list/memorial_lists.tsv", encoding="UTF-8", sep="\t", 
                        select = selected_vars, quote="", stringsAsFactors = TRUE)

translations <- read_excel(here::here("data/ethnicity_translations.xlsx"))

```



```{r}
memorial_lists <-
  memorial_lists %>% 
  left_join(translations, by = "nation") %>% 
  mutate(ethnicity = as.factor(ifelse(is.na(ethnicity), "Other", ethnicity)))  

data_labeled <- memorial_lists[!memorial_lists$ethnicity %in% c("Missing", "Other"),]
data_missing <- memorial_lists[memorial_lists$ethnicity  == "Missing",]
rm(memorial_lists)
rm(translations)
gc()

data_labeled_person_id <- data_labeled$person_id
data_labeled$ethnicity <- droplevels(data_labeled$ethnicity)

data_labeled <- data_labeled %>% 
  dplyr::select(ethnicity, surname, name , patronimic)
```


```{r}
set.seed(2019)
folds <- sample(1:10, size = nrow(data_labeled), replace = T)

CV_nb <- lapply(1:10, function(x){ 
  nb <- nb('ethnicity', data_labeled)
  model <- lp(nb, data_labeled[folds != x,] , smooth = 0.005)
  preds <- predict(model,  data_labeled[folds == x,])
  return(data.frame(preds, ethnicity = data_labeled$ethnicity[folds == x]))
})

CV_nb <- do.call(rbind, CV_nb)
conf_matrix <- confusionMatrix(CV_nb$preds, CV_nb$ethnicity)

saveRDS(conf_matrix, file = here::here("data/conf_matrix.RData"))
rm(list = c("CV_nb", "folds", "conf_matrix"))
gc()
```


```{r}
nb <- nb('ethnicity', data_labeled)
nb_model <- lp(nb, data_labeled , smooth = 0.005)

data_missing$ethnicity <- predict(nb_model, data_missing)
data_labeled$person_id <- data_labeled_person_id
data_missing <- data_missing %>% 
  dplyr::select(ethnicity, surname, name , patronimic, person_id)
```

```{r}
events_preds <- 
  bind_rows(data_labeled, data_missing, .id = "id") %>% 
  mutate(prediction = ifelse(id == 1, 0, 1)) %>% 
  dplyr::select(person_id, -id, everything())

fwrite(events_preds, here::here("data/events_predictions.csv"))

```

