---
title: "ethnicity_names"
author: "Martin Kosík"
date: "12 ledna 2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(stringi)
library(here)
library(tidyverse)
library(data.table)
library(broom)
```

## R Markdown

```{r}
load("data/eventsClean_v1.RData")
names(events)
events <- as.data.table(events)
table(events$SOURCE)
str(events)
Sys.setlocale("LC_CTYPE", "russian") 
stri_trans_general(head(events$SOURCE), "russian-latin/bgn")
events$SOURCE_latin <- stri_trans_general(events$SOURCE, "cyrillic-latin")
events$NAME_latin <- stri_trans_general(events$NAME, "russian-latin/bgn")

events <- head(events) %>% 
  mutate(surname = extract2(str_split(NAME, pattern = " ", n = 2))) %>% 
  unnest()

events$surname <-  str_split(events$NAME, pattern = " ", n = 2) %>% 
  map_chr(1)

events$surname_latin <- stri_trans_general(events$surname, "cyrillic-latin")

events %>% 
  filter(ETHNIC_GER == 1) %>% 
  select(NAME, NAME_latin, surname, surname_latin) %>% 
  count(surname, surname_latin, sort = T) %>% 
  write_csv(here("data/german_surnames.csv"))



```

```{r}
german_surnames <- read_csv(here("data/german_surnames.csv"))

ger_surnames_vec <- german_surnames %>% 
  filter(n > 3) %>%
  pull(surname)


rm(german_surnames)  

gc()

events <- events %>% 
  mutate(ger_surname = ifelse(surname %in% ger_surnames_vec, 1, 0))

events <- events %>% 
  select(-c(GULAG_RAILMED:CENT_DEGREE_R))

events <- events %>% 
  left_join(filter(german_surnames, n > 4), c("surname"))

events$ger_surname <- ifelse(is.na(events$n), 0, 1)
```

```{r}
save(events, file = here("data/eventsClean_v2.RData"))
```


```{r}
events %>% 
  filter(!is.na(n)) %>% 
  count(ETHNIC_GER)
```


```{r}
events %>% 
  select(ETHNIC_TA, NAME, NAME_latin) %>% 
  filter(ETHNIC_TATAR == 1) %>% 
  sample_n(1000)
```

```{r}
min_by_year_sur <- events %>%
  select(YEAR, ETHNIC_BEL:ETHNIC_CHECHEN, ger_surname) %>% 
  group_by_all() %>% 
  count() %>% 
  ungroup()
  
write_csv(min_by_year_sur, here("data/min_arrests_by_year_ger_surname.csv"))

```

```{r}
min_by_year_sur <- read_csv(here("data/min_arrests_by_year_ger_surname.csv"))

min_by_year_sur <- min_by_year_sur %>% 
  ungroup() %>% 
  mutate(both_eth_sur_ger = ifelse(ETHNIC_GER == 1 & ger_surname == 1, 1, 0)) %>% 
  mutate(n_of_eth_gr = rowSums(.[c(2:19, 21)])) %>%  
  filter(n_of_eth_gr == 1 | (both_eth_sur_ger == 1 & n_of_eth_gr == 3)) %>% 
  select(-n_of_eth_gr) %>% 
  mutate(ETHNIC_GER = ifelse(both_eth_sur_ger == 1, 0, ETHNIC_GER),
         ger_surname = ifelse(both_eth_sur_ger == 1, 0, ger_surname)) %>% 
  gather(key= "ethnicity", value = "value", -c(YEAR, n)) %>% 
  filter(value == 1) %>% 
  select(-value)  


min_by_year_sur <- min_by_year_sur %>% 
  complete(YEAR, ethnicity, fill = list(n = 0)) %>% 
  filter(YEAR >= 1921) %>% 
  mutate(ethnicity = str_remove(ethnicity, "ETHNIC_"), 
         ethnicity = case_when(ethnicity == "BEL" ~ "Belarussian",
                               ethnicity == "GER" ~ "German",
                               ethnicity == "POL" ~ "Polish",
                               ethnicity == "UKR" ~ "Ukrainian",
                               TRUE ~ ethnicity) %>% 
                      str_to_title() %>% 
                      as.factor())

```

```{r}
min_by_year_sur %>% 
  count(ethnicity)

min_by_year_sur %>% 
  filter(ethnicity %in% c("German", "Both_eth_sur_ger")) %>% 
  summarize(total = sum(n))

min_by_year_sur %>% 
  filter(ethnicity %in% c("Ger_surname", "German", "Both_eth_sur_ger")) %>% 
  ggplot(aes(YEAR, log_n, color = ethnicity)) + geom_line() + theme_light() + 
  labs(title = "Arrests of Germans by source of identification")
```

```{r}
min_by_year_sur %>% 
  filter(ethnicity %in% c("Ger_surname", "German", "Both_eth_sur_ger")) %>% 
  spread(key = "ethnicity", value = "n") %>% 
  mutate(surname = Both_eth_sur_ger + Ger_surname, 
         label = Both_eth_sur_ger + German) %>% 
  gather(key = "source", value = "n", -YEAR) %>% 
  filter(!source %in% c("Ger_surname", "German", "Both_eth_sur_ger")) %>% 
  mutate(log_n = log(1 + n)) %>% 
  ggplot(aes(YEAR, log_n, color = source)) + geom_line() + theme_light() + 
  labs(title = "Arrests of Germans (in log) by source of identification of their ethnicity", x = "Year") + 
  guides(color=guide_legend(title="Source")) + 
  scale_color_manual(labels = c("Label in the data", "Surname"), values = c("red","blue"))

ggsave(here("plots/ger_arrests_surname_vs_label.pdf"))
```

```{r}
min_by_year_sur <- min_by_year_sur %>% 
  spread(key = "ethnicity", value = "n") %>% 
  mutate(ger_surname = Both_eth_sur_ger + Ger_surname) %>% 
  gather(key = "ethnicity", value = "n", -YEAR) %>% 
  filter(!ethnicity %in% c("Ger_surname", "German", "Both_eth_sur_ger")) %>% 
  mutate(log_n = log(1 + n), 
         ethnicity = str_replace(ethnicity, "ger_surname", "German") %>% 
           as.factor(), 
         german = ifelse(ethnicity == "German", 1, 0)) 

```

```{r}
years <- 1930:1938

post_year_dummies <- map_dfc(years, ~  as.numeric(min_by_year_sur$YEAR >= .)) %>% 
  rename_all( funs( c(paste0("post_" ,years))))

min_by_year_sur <-bind_cols(min_by_year_sur, post_year_dummies)
```

```{r}
fmla <- as.formula(paste("log_n ~ ", 
                         paste0("german:","post_", years, collapse = " + "),  "+ as.factor(YEAR) +
                         ethnicity + ethnicity: YEAR"))

diff_model <- lm(fmla,  data = min_by_year_sur)

diff_model_restr <- lm(fmla,  data = filter(min_by_year_sur, YEAR <= 1945))

tidy(diff_model, conf.int = T) %>% 
  View()


```

```{r}
load("data/eventsClean_v1.RData")

events <- events[, c("AID", "YEAR", "MONTH", "DAY")] 


events_pred <- read_csv(here::here("data/events_predictions.csv"))

events <- events %>% 
  left_join(events_pred, by = "AID") 

rm(events_pred)
gc()

pred_by_year <- events %>% 
  filter(!is.na(ethnicity)) %>% 
  count(prediction, YEAR, ethnicity) %>% 
  complete(YEAR, ethnicity, prediction, fill = list(n = 0)) %>% 
  mutate(log_n = log(1 + n),
         source = ifelse(prediction == 1, "prediction", "label")) %>% 
  filter(YEAR >= 1921)

pred_by_year %>% 
  ggplot(aes(x = YEAR, y = log_n, col = source)) + geom_line() + facet_wrap(~ethnicity) +
  labs(y = "log(1 + y)", x = "year", col ="source", caption = "annual observations") + theme_bw() 
 
ggsave(here::here("plots/arrests/annual_pred_vs_label.pdf"))

```

