---
title: "missing_data_analysis"
author: "Martin Kosík"
date: "27 února 2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(lubridate)
library(scales)
```

```{r}
events <- readRDS(here::here("data/eventsClean_v2.RData"))

by_year <- events %>% 
  count(YEAR, MONTH, prediction, ethnicity) 

events %>% 
  count(YEAR, prediction, ethnicity) %>% 
  filter(is.na(YEAR), !is.na(prediction)) %>% 
  mutate(ethnicity = fct_reorder(ethnicity, n)) %>% 
  ggplot(aes(ethnicity, n)) + geom_col() + facet_wrap(~ prediction, scales = "free_x", ncol = 1) + coord_flip() +
  scale_y_log10()

events %>% 
  count(YEAR, prediction) %>% 
  filter(!is.na(YEAR), !is.na(prediction), YEAR >= 1921) %>% 
  mutate(prediction = ifelse(prediction == 1, "missing", "not missing"),
         YEAR = as_date(str_c(YEAR, "-01-01"))) %>% 
  ggplot(aes(x = YEAR, y = n, fill = prediction)) + geom_col(position = "fill") + theme_minimal() +
  labs(y = element_blank(), x = "Year", fill = "Information on ethnicity") + 
  theme(#panel.grid.major.x = element_blank(), 
        panel.grid.minor.x = element_blank(), 
        text = element_text(size=12)) +
  scale_x_date(date_minor_breaks = "1 year", date_breaks = "3 year", date_labels = "%Y")

ggsave(here::here("plots/missing_data_analysis/proportion_by_year.pdf"))

events %>% 
  count(YEAR, prediction) %>% 
  filter(!is.na(YEAR), !is.na(prediction), YEAR >= 1921) %>% 
  mutate(prediction = ifelse(prediction == 1, "missing", "not missing"),
         YEAR = as_date(str_c(YEAR, "-01-01"))) %>% 
  ggplot(aes(x = YEAR, y = n, fill = prediction)) + geom_col() + theme_minimal() +
  labs(y = element_blank(), x = "Year", fill = "Information on ethnicity") + 
  theme(#panel.grid.major.x = element_blank(), 
        panel.grid.minor.x = element_blank(), 
        text = element_text(size=12)) +
  scale_x_date(date_minor_breaks = "1 year", date_breaks = "3 year", date_labels = "%Y") +
  scale_y_continuous(labels = comma)

ggsave(here::here("plots/missing_data_analysis/count_by_year.pdf"))


events %>% 
  count(YEAR, prediction, ethnicity) %>% 
  filter(is.na(YEAR), !is.na(prediction)) %>% 
  mutate(ethnicity = fct_reorder(ethnicity, n, sum),
         prediction = as.factor(prediction)) %>% 
  ggplot(aes(ethnicity, n, fill = prediction)) + geom_col(position = "fill") + coord_flip() #+ scale_y_log10()

by_year %>% 
  mutate(log_n = log(1 + n)) %>% 
  ggplot(aes(x = YEAR, y = log_n, col = as.factor(prediction))) + geom_line() +
  facet_wrap(~ ethnicity, scales = "free_y") + theme_bw()


by_year %>% 
  complete(YEAR,  ethnicity, prediction, fill = list(n = 0)) %>% 
  mutate(prediction = ifelse(prediction == 1, "prediction", "label")) %>% 
  spread(key = prediction, value = n) 

min_by_month_all %>%
  mutate(year = year(date)) %>% 
  group_by(year, ethnicity) %>% 
  summarize_at(vars(label, pred_adj_scaled, n), sum) %>% 
  ungroup() %>% 
  mutate(diffrence = pred_adj_scaled - label, 
         log_diff = log(1 + abs(diffrence)),
         sgn_log_diff = sign(diffrence) * log_diff) %>% 
  ggplot(aes(x = year, y = sgn_log_diff)) + geom_line() + facet_wrap(~ethnicity) +
  labs(y = "log(1 + y)", x = "year") + theme_bw()

  
```

```{r}
min_by_month_preds <- events %>% 
  count(YEAR, MONTH, prediction, ethnicity) %>% 
  filter(YEAR >= 1921, !is.na(ethnicity), !is.na(YEAR), !is.na(MONTH)) %>% 
  mutate(date = as_date(str_c(YEAR,  MONTH, "01", sep = "-"))) %>% 
  complete(date, ethnicity, prediction, fill = list(n = 0)) %>% 
  dplyr::select(-c(YEAR, MONTH))


conf_matrix <- readRDS(here::here("data/conf_matrix.RData"))

spec_sens_data <- as_tibble(conf_matrix$byClass, rownames = "ethnicity") %>% 
  mutate(ethnicity = str_replace(ethnicity, "Class: ", "")) %>% 
  dplyr::select(ethnicity:Specificity)

conf_matrix <- conf_matrix$table
conf_matrix <- apply(conf_matrix, 2, function(x) x/sum(x))


min_by_month_all <- min_by_month_preds %>% 
  mutate(prediction = ifelse(prediction == 1, "prediction", "label")) 


pred_adj_full_by_month <- min_by_month_all %>% 
  filter(prediction == "prediction") %>% 
  dplyr::select(-prediction) %>% 
  nest(-date) %>% 
  mutate(pred_adj_full = map(data, ~ solve(conf_matrix, .$n))) %>% 
  unnest(pred_adj_full, data) %>% 
  mutate(pred_adj_full = ifelse(pred_adj_full < 0, 0, pred_adj_full)) %>% 
  dplyr::select(-n)
  
  

min_by_month_all <- min_by_month_all %>% 
  spread(key = prediction, value = n) %>% 
  left_join(spec_sens_data, by = "ethnicity") %>% 
  left_join(pred_adj_full_by_month, by = c("date", "ethnicity")) %>% 
  group_by(date) %>% 
  add_tally(wt = prediction) %>% 
  ungroup() %>% 
  rename(total_pred_by_date = n) %>% 
  mutate(pred_adj = (prediction - total_pred_by_date * (1 - Specificity))/(Sensitivity + Specificity -1),
         pred_adj = ifelse(pred_adj < 0, 0, pred_adj),
         german = ifelse(ethnicity == "German", 1, 0)) %>% 
  add_tally(wt = prediction) %>% 
  rename(total_pred = n) %>% 
  add_tally(wt = pred_adj) %>% 
  rename(total_pred_adj = n) %>% 
  add_tally(wt = pred_adj_full) %>% 
  rename(total_pred_adj_full = n) %>% 
  mutate(pred_adj_scaled = round(pred_adj * (total_pred/total_pred_adj)),
         pred_adj_full_scaled = round(pred_adj_full * (total_pred/total_pred_adj_full)),
         n = label + pred_adj_full_scaled, 
         log_n = log(1 + n))


min_by_month_all %>% 
  summarise(pred_adj = sum(pred_adj), prediction = sum(prediction), label = sum(label),
            pred_adj_scaled = sum(pred_adj_scaled), pred_adj_full_scaled = sum(pred_adj_full_scaled))

```


```{r}
min_by_q <-  min_by_month_all %>% 
  mutate(year_q = quarter(date, with_year = T),
         year_q_date = floor_date(date, unit = "quarter")) %>% 
  group_by(year_q, year_q_date, ethnicity, german) %>% 
  summarize(n = sum(n)) %>% 
  ungroup() %>% 
  mutate(log_n = log(n + 1)) %>% 
  group_by(ethnicity) %>% 
  mutate(t = row_number()) %>% 
  ungroup() %>% 
  mutate(pre_treatment = ifelse(year_q_date >= "1928-01-01" & year_q_date <= "1933-01-01", 1, 0),
         hostility = ifelse(year_q_date >= "1933-03-23" & year_q_date <= "1939-08-23", 1, 0), 
         pact = ifelse(year_q_date > "1939-08-23" & year_q_date < "1941-06-22", 1, 0), 
         war = ifelse(year_q_date >= "1941-06-22" & year_q_date < "1945-05-08", 1, 0),
         post_war = ifelse(year_q_date >= "1945-05-08", 1, 0), 
         ethnicity = as.factor(ethnicity)) 

```

