---
title: "Naive bayes"
author: "Martin Kosík"
date: "8 února 2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(broom)
library(data.table)
library(lubridate)
library(here)
library(caret)
library(naivebayes)
library(bnclassify)
library(klaR)
library(rsample)
library(yardstick)
library(widyr)
library(stringi)
```


```{r }
Sys.setlocale("LC_CTYPE", "russian") 


load("data/eventsClean_v1.RData")

```

We filter out those wtih multiple ethnicities
```{r}
events$SOURCE_latin <- stri_trans_general(events$SOURCE, "cyrillic-latin")

events %>% 
  count(SOURCE_latin, SOURCE, sort = T) %>% 
  View()


events %>% 
  filter(SENTENCE_RESETTLE == 1, ETHNIC_GER == 1) %>% 
  count(YEAR) %>% 
  View()


events <- events %>% 
  mutate(ETHNIC_KALMYK = ifelse(SOURCE == "Книга памяти ссылки калмыцкого народа", 1, ETHNIC_KALMYK),
         YEAR = ifelse(SOURCE == "Книга памяти ссылки калмыцкого народа", 1944, YEAR),
         #MONTH = ifelse(SOURCE == "Книга памяти ссылки калмыцкого народа", 1, MONTH),
         n_of_eth_gr = rowSums(.[37:54]))

events %>% 
  count(n_of_eth_gr, sort = T)

events <- events %>% 
  filter(n_of_eth_gr <= 1) %>% 
  dplyr::select(AID, NAME, starts_with("ETHNIC_"))


```

```{r}

minorities_var_names <- names(events) %>% 
  str_subset("ETHNIC_")

events <- as.data.table(events)

events_long <- melt(events, id.vars = "AID",
                measure.vars = minorities_var_names, 
                variable.name = "ethnicity")[
                  value == 1][,ethnicity := str_remove(ethnicity, "ETHNIC_")][,
                    ethnicity :=  case_when(ethnicity == "BEL" ~ "Belarussian",
                                            ethnicity == "RUS" ~ "Russian",
                               ethnicity == "GER" ~ "German",
                               ethnicity == "POL" ~ "Polish",
                               ethnicity == "UKR" ~ "Ukrainian",
                               TRUE ~ ethnicity) %>% 
                      str_to_title()][, value := NULL]

events <- events %>% 
  left_join(events_long, "AID")

rm(events_long)
gc()

```

```{r}
events <- events %>% 
  mutate(names_split = str_split(NAME, pattern = " "),
         first_name = as.factor(map_chr(names_split, nth, 2)),
         surname = as.factor(map_chr(names_split, 1)),
         number_of_names = as.factor(map_int(names_split, length)),
         ethnicity = as.factor(ethnicity)) %>% 
  dplyr::select(-c(names_split, NAME))

saveRDS(events, file = here::here("data/eventsClean_v2.RData"))

events <- readRDS(here::here("data/eventsClean_v2.RData"))

```

```{r}

train_data <- filter(events, !is.na(ethnicity))
split <- initial_split(filter(events, !is.na(ethnicity)), prop = .85, strata = "ethnicity")
train <- training(split)
test  <- testing(split)

```


```{r}
# create response and feature data
x <- train[, c("surname", "first_name")]
y <- train$ethnicity

train <- droplevels(train)
test <- droplevels(test)

test$surname <- factor(as.character(test$surname), levels = levels(train$surname))
test$first_name <- factor(as.character(test$first_name), levels = levels(train$first_name))
test$number_of_names <- factor(as.character(test$number_of_names), levels = levels(train$number_of_names))

sum(is.na(test$surname))
length(levels(test$surname))



# results

flat_prior <- rep(1/18, 18)

nb_flat_prior <- naive_bayes(ethnicity ~  number_of_names, data = train, 
                             laplace = 1, usekernel = FALSE)

nb_klaR <- NaiveBayes(ethnicity ~ surname + first_name + number_of_names, data = train, 
                             fL = 1, usekernel = FALSE)

nb_e <- naiveBayes(ethnicity ~ surname + first_name + number_of_names, data = train, 
                             fL = 1, usekernel = FALSE)

confusionMatrix(predict(nb_flat_prior), train$ethnicity)
confusionMatrix(predict(nb_e, train), train$ethnicity)

confusionMatrix(predict(nb_e, newdata = test[, c("surname", "first_name", "number_of_names")]), test$ethnicity)
confusionMatrix(predict(nb_e, newdata = train[, c("surname", "first_name", "number_of_names")]), train$ethnicity)


test$probability <- predict(nb_klaR, test)$posterior




set.seed(2019)
folds <- sample(1:10, size = nrow(train_data), replace = T)
table(folds)

CV_nb <- lapply(1:10, function(x){ 
  model <- NaiveBayes(ethnicity ~ surname + first_name + number_of_names, data = train_data[folds != x,], 
                             fL = 1, usekernel = FALSE)
  preds <- predict(model,  train_data[folds == x,])$class
  return(data.frame(preds, ethnicity = train_data$ethnicity[folds == x]))
})

CV_nb <- do.call(rbind, CV_nb)
conf_matrix <- confusionMatrix(CV_nb$preds, CV_nb$ethnicity)



saveRDS(conf_matrix, file = here::here("data/conf_matrix.RData"))


con_matrix_adj <- confusionMatrix(test_eth_adj, test$ethnicity)
con_matrix_adj$byClass


con_matrix <- conf_mat(test, truth = ethnicity, estimate = prediction)
accuracy(test, truth = ethnicity, estimate = prediction)
test %>%
 # group_by(ethnicity) %>% 
  precision(truth = ethnicity, estimate = prediction)

test %>%
  group_by(ethnicity) %>% 
  do(Sensitivity = sens(., "ethnicity", "prediction"),
     Specificity = spec(., "ethnicity", "prediction")) %>% unnest


predict.naive_bayes(nb_flat_prior, newdata = test)
head(predict(nb_flat_prior, type = "class"))
str(train)

browseVignettes("bnclassify")
nb <- nb('ethnicity', dataset = dplyr::select(train,ethnicity,  surname, first_name, number_of_names) ,
         features = c("surname", "first_name", "number_of_names")) # Learn parameters 
cv(nb, dplyr::select(train,ethnicity,  surname, first_name, number_of_names), k = 4) # 10-fold Cross-validation 

ll <- tan_cl('ethnicity', dataset =  dplyr::select(train,ethnicity,  surname, first_name, number_of_names),
              score = 'aic')

head(predict(nb, dplyr::select(test,ethnicity,  surname, first_name, number_of_names)))


confusionMatrix(predict(nb, dplyr::select(test,ethnicity,  surname, first_name, number_of_names)), test$ethnicity)
confusionMatrix(predict(nb, dplyr::select(train,ethnicity,  surname, first_name, number_of_names)), train$ethnicity)

save(nb.m1, file = "nb_model")
```

Splitting the data based on whether we have information on ethnicity
```{r}
events_labeled <- events[!is.na(events$ethnicity), ]
events_missing <- events[is.na(events$ethnicity), ]


rm(events)
gc()
```

```{r}
nb_klaR <- NaiveBayes(ethnicity ~ surname + first_name + number_of_names, data = events_labeled, 
                             fL = 1, usekernel = FALSE)



nb <- nb('ethnicity', dataset = dplyr::select(events_labeled, ethnicity,  surname, first_name, number_of_names) ,
         features = c("surname", "first_name", "number_of_names")) # Learn parameters 
nb <- lp(nb, dplyr::select(events_labeled, ethnicity,  surname, first_name, number_of_names), smooth = 1)

confusionMatrix(predict(nb_klaR)$class, events_labeled$ethnicity)


events_missing$ethnicity <- predict(nb_klaR, events_missing)$class
events_missing$probability <- predict(nb_klaR, events_missing)$posterior

confusionMatrix(predict(nb, dplyr::select(events_labeled, ethnicity,  surname, first_name, number_of_names)), events_labeled$ethnicity)


events_missing$ethnicity <- predict(nb, 
                                    dplyr::select(events_missing, ethnicity,  surname, first_name, number_of_names))
events_missing$probability <-predict(nb, 
                                    dplyr::select(events_missing, ethnicity,  surname, first_name, number_of_names),
                                    prob = TRUE)


sum(is.na(events_missing$ethnicity))

```

```{r}
events_labeled <- fread(here::here("data/events_labeled.csv"), encoding = "UTF-8")
events_labeled <- events_labeled %>% 
  mutate(probability = as.numeric(NA))

events_preds <- 
  bind_rows(events_labeled, events_missing, .id = "id") %>% 
  mutate(prediction = ifelse(id == 1, 0, 1)) %>% 
  dplyr::select(-starts_with("ETHNIC_"))
  
events_preds <- 
  rbind(events_labeled, events_missing) %>% 
  mutate(prediction = ifelse(n_of_eth_gr == 0, 1, 0)) %>% 
  dplyr::select(-c(n_of_eth_gr))
  

fwrite(events_preds, here::here("data/events_predictions.csv"))

```


