---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

Load the necessary packages
```{r setup}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(broom)
library(lubridate)
library(stargazer)
library(here)
library(estimatr)
library(writexl)
```



```{r}
min_by_month <- min_by_month %>% 
  complete(date_ym, ethnicity, fill = list(n = 0)) %>% 
  filter(date_ym >= 1921) %>% 
  mutate(ethnicity = str_remove(ethnicity, "ETHNIC_"), 
         ethnicity = case_when(ethnicity == "BEL" ~ "Belarussian",
                               ethnicity == "GER" ~ "German",
                               ethnicity == "POL" ~ "Polish",
                               ethnicity == "UKR" ~ "Ukrainian",
                               TRUE ~ ethnicity) %>% 
                      str_to_title() %>% 
                      as.factor(),
         german = ifelse(ethnicity == "German", 1, 0))

```


```{r}
min_by_month <- min_by_month %>% 
  mutate(date = as_date(date_ym), 
         ym_chr = str_sub(date , end = -4),
         log_n = log(1 + n), 
         pre_treatment = ifelse(date >= "1928-01-01" & date <= "1933-03-23", 1, 0),
         hostility = ifelse(date >= "1933-03-23" & date <= "1939-08-23", 1, 0), 
         pact = ifelse(date > "1939-08-23" & date < "1941-06-22", 1, 0), 
         war = ifelse(date >= "1941-06-22" & date < "1945-05-08", 1, 0),
         post_war = ifelse(date >= "1945-05-08", 1, 0)) %>% 
  group_by(ethnicity) %>% 
  mutate(t = row_number()) %>% 
  ungroup()



write_csv(min_by_month, here::here("data/cleaned_min_arrests_by_month.csv"))  

```
The key dates are:
1. Hitler becomes a dictator 1933-03-23
2. Molotov-Ribentropp pact is signed 1939-08-23
3. Operation Barbarossa is launched 1941-06-22 (we )
4. End of WWII in Europe 1945-05-08
```{r}
min_by_month <- read_csv(here::here("data/cleaned_min_arrests_by_month.csv"))


min_by_q <-  min_by_month %>% 
  mutate(year_q = quarter(date, with_year = T),
         year_q_date = floor_date(date, unit = "quarter")) %>% 
  group_by(year_q, year_q_date, ethnicity, german) %>% 
  summarize(n = sum(n)) %>% 
  ungroup() %>% 
  mutate(log_n = log(n + 1)) %>% 
  group_by(ethnicity) %>% 
  mutate(t = row_number()) %>% 
  ungroup() %>% 
  mutate(pre_treatment = ifelse(year_q_date >= "1928-01-01" & year_q_date <= "1933-01-01", 1, 0),
         hostility = ifelse(year_q_date >= "1933-03-23" & year_q_date <= "1939-08-23", 1, 0), 
         pact = ifelse(year_q_date > "1939-08-23" & year_q_date < "1941-06-22", 1, 0), 
         war = ifelse(year_q_date >= "1941-06-22" & year_q_date < "1945-05-08", 1, 0),
         post_war = ifelse(year_q_date >= "1945-05-08", 1, 0), 
         ethnicity = as.factor(ethnicity)) 

```

```{r}
year_quarters <- crossing(year = 1928:1955, quarter = 1:4) %>% 
  mutate(yq = str_c(year, quarter, sep = ".")) %>% 
  pull(yq)

max(min_by_q$year_q)

tail(post_yq_dummies$post_1955.4)

yq_dummies <- map_dfc(year_quarters, ~  if (dplyr::last(year_quarters) == .){
                                                    as.numeric(min_by_q$year_q >= .)} else {
                                                    as.numeric(min_by_q$year_q == .)}) %>% 
  rename_all( funs( c(paste0("year_" ,year_quarters))))

min_by_q <-bind_cols(min_by_q, yq_dummies)

```

```{r}
fmla <- as.formula(paste("log_n ~ ", 
                         paste0("german:","year_", year_quarters, collapse = " + "),  "+ as.factor(year_q) +
                                                 ethnicity + t:ethnicity+ ethnicity:I(t^2)"))

fmla_window <- as.formula(paste("log_n ~ german:hostility + german:pact + german:war +  german:post_war +
                                as.factor(year_q) + ethnicity + ethnicity:t + ethnicity:I(t^2)"))

fmla_window_pre_treat <- as.formula("log_n ~ german:pre_treatment + german:hostility + german:pact +
                                    german:war +  german:post_war +  as.factor(year_q) + 
                                    ethnicity + ethnicity:t + ethnicity:I(t^2)")


diff_model <- lm(fmla,  data = min_by_q)
diff_model_window <- lm(fmla_window,  data = min_by_q)
diff_model_window_pre_treat <- lm(fmla_window_pre_treat,  data = min_by_q)

diff_model_robust <- lm_robust(fmla, min_by_q, clusters = ethnicity, se_type = "stata")
diff_model_robust <- commarobust(diff_model, clusters = min_by_q$ethnicity, se_type = "CR2")
diff_model_window_robust <- commarobust(diff_model, clusters = min_by_q$ethnicity, se_type = "CR2")
diff_model_window_pre_treat_robust <- commarobust(diff_model_window_pre_treat, clusters = min_by_q$ethnicity, se_type = "stata")

estimatr::tidy(diff_model_robust)
class(min_by_q$ethnicity)
summary(diff_model_window)
```

```{r}
library(zoo)
diff_model_robust %>% 
  broom::tidy(conf.int = TRUE) %>% 
  filter(str_detect(term, "german:")) %>% 
  left_join(estimatr::tidy(diff_model_robust), by = "term", suffix = c("", "_robust")) %>% 
  mutate(nice_labs = str_replace(term,"german:year_","") %>% 
           str_replace("\\.", " Q") %>% 
           as.yearqtr() %>% 
           as.Date(), 
         conf.low_min = map2_dbl(conf.low, conf.low_robust, min), 
         conf.high_max = map2_dbl(conf.high, conf.high_robust, max)) %>% 
  ggplot(mapping = aes(x = nice_labs, y = estimate, ymin = conf.low_min, ymax = conf.high_max, group = 1))+ 
  geom_vline(xintercept= ymd(c(19330323, 19390823, 19410622)), col = "red", linetype = "dashed") +
  geom_pointrange()+  geom_hline(yintercept= 0) + theme_bw() + 
  scale_x_date(date_minor_breaks = "1 year", date_breaks = "2 year", date_labels = "%Y")+
  labs(x = "year", 
       caption = "error bars show 95% confidence intervals \n 
                    SE are based on estimator by Pustejovsky and Tipton (2018)",
       title = "Estimates on quarterly interactions of german*post")

diff_model_robust %>% 
  estimatr::tidy(conf.int = TRUE) %>% 
 # broom::tidy(conf.int = TRUE) %>% 
  filter(str_detect(term, "german:")) %>% 
  mutate(nice_labs = str_replace(term,"german:year_","") %>% 
           str_replace("\\.", " Q") %>% 
           as.yearqtr() %>% 
           as.Date()) %>% 
  ggplot(mapping = aes(x = nice_labs, y = estimate, ymin = conf.low, ymax = conf.high, group = 1))+ 
  geom_vline(xintercept= ymd(c(19330323, 19390823, 19410622)), col = "red", linetype = "dashed") +
  geom_pointrange()+  geom_hline(yintercept= 0) + theme_bw() + 
  scale_x_date(date_minor_breaks = "1 year", date_breaks = "2 year", date_labels = "%Y")+
  labs(x = "year", 
       caption = "error bars show 95% confidence intervals \n 
                    SE are based on the small-sample cluster-robust estimator by Pustejovsky and Tipton (2018)",
       title = "Estimates on interactions of german*year-quarter")

ggsave(here::here("plots/effects/quarterly/pointrange_robust.pdf"))

ser_cor_model <- function(df) {
  lm(.resid ~ res_lag, data = df)
}

german_res <- diff_model %>% 
  broom::augment(conf.int = TRUE) %>%
  mutate(res_lag = dplyr::lag(.resid)) %>% 
  select(-contains("year")) %>% 
  nest(-ethnicity) %>% 
  mutate(ser_cor_model = map(data, ser_cor_model),
         coefs = map(ser_cor_model, broom::tidy, conf.int = T)) %>% 
  unnest(coefs) %>% 
  filter(term == "res_lag")

german_res %>% 
  ggplot(aes(ethnicity, estimate)) + geom_point()

```


```{r}
diff_model %>% 
  broom::tidy(conf.int = TRUE) %>% 
  filter(str_detect(term, "german:")) %>% 
  left_join(estimatr::tidy(diff_model_robust), by = "term", suffix = c("", "_robust")) %>% 
  mutate(nice_labs = str_replace(term,"german:post_","") %>% 
           str_replace("\\.", " Q") %>% 
           as.yearqtr() %>% 
           as.Date(), 
         conf.low_min = map2_dbl(conf.low, conf.low_robust, min), 
         conf.high_max = map2_dbl(conf.high, conf.high_robust, max)) %>% 
  ggplot(mapping = aes(x = nice_labs))+ 
  geom_ribbon(aes(ymin = conf.low_min, ymax = conf.high_max), fill = "grey70")+
  geom_line(aes(y = estimate), col = "black") + geom_point(aes(y = estimate)) +
  theme_bw() +  geom_hline(yintercept= 0, col = "black", linetype = "dashed") +
  scale_x_date(date_minor_breaks = "1 year", date_breaks = "2 year", date_labels = "%Y") + 
  geom_vline(xintercept = ymd(c(19330323, 19390823, 19410622)), color = "red") +
  labs(x = "year",
       caption = "the shaded ares shows 95% confidence intervals \n 
                    SE are maximum of their cluster robust and standard versions",
       title = "Estimates on quarterly interactions of german*year/quarter")

ggsave(here::here("plots/effects/quarterly/line.pdf"))

```

```{r time window effects plot}
diff_model_window %>% 
  broom::tidy(conf.int = TRUE) %>% 
  filter(str_detect(term, "german:")) %>% 
  mutate(nice_labs = str_replace(term,"german:","")) %>% 
  ggplot(mapping = aes(x = nice_labs, y = estimate, ymin = conf.low, ymax = conf.high, group = 1))+ 
  geom_pointrange()+  geom_hline(yintercept= 0) + theme_minimal() +
  theme(axis.line = element_line(size = 1), 
        panel.grid.major.x = element_blank(), panel.grid.minor.x = element_blank(), 
        text = element_text(size=15)) + 
  labs(x = element_blank(), caption = "error bars show 95% confidence intervals",
       title = "Interactions of German ethnicity with specified time window dummy", 
       subtitle = "Quarterly obseravations") + 
  scale_x_discrete(labels = c('Hostility without war \n (1933 Q2 to 1939 Q3)',
                              'Pact \n (1939 Q4 to 1941 Q2)', 'War \n (1941 Q3 to 1945 Q2)',
                              "Post-war \n (from 1945 Q3)"))


ggsave(here::here("plots/did_effects_quart_window_postwar.pdf"))
```

```{r}
diff_model_window_pre_treat %>% 
  broom::tidy(conf.int = TRUE) %>% 
  filter(str_detect(term, "german:")) %>% 
  left_join(estimatr::tidy(diff_model_window_pre_treat, conf.int = TRUE),
            by = "term", suffix = c("", "_robust")) %>% 
  mutate(nice_labs = str_replace(term,"german:","") %>% 
           fct_relevel("pre_treatment", "hostility", "pact", "war", "post_war"),
         conf.low_min = map2_dbl(conf.low, conf.low_robust, min), 
         conf.high_max = map2_dbl(conf.high, conf.high_robust, max)) %>% 
  ggplot(mapping = aes(x = nice_labs, y = estimate, ymin = conf.low_min, ymax = conf.high_max, group = 1))+ 
  geom_pointrange()+  geom_hline(yintercept= 0) + theme_minimal() +
  theme(axis.line = element_line(size = 1), 
        panel.grid.major.x = element_blank(), panel.grid.minor.x = element_blank(), 
        text = element_text(size=15)) + 
  labs(x = element_blank(),
       caption = "error bars show 95% confidence intervals \n 
                    SE are maximum of their cluster robust and standard versions",
       title = "Interactions of German ethnicity with specified time window dummy", 
       subtitle = "Quarterly obseravations") + 
  scale_x_discrete(labels = c("Pre-tretment \n (1928 Q1 to 1933 Q1)",
                              'Hostility without war \n (1933 Q2 to 1939 Q3)',
                              'Pact \n (1939 Q4 to 1941 Q2)', 'War \n (1941 Q3 to 1945 Q2)',
                              "Post-war \n (from 1945 Q3)"))

ggsave(here::here("plots/effects/quarterly/pre_treatment.pdf"))


```


```{r}
min_by_q %>% 
  ggplot(aes(x = year_q_date, y = log_n)) + geom_line() + facet_wrap(~ethnicity) +
  labs(y = "log(1 + y)", x = "year") + theme_bw()

ggsave(here("plots/arrests_by_ethnicity_quart.pdf"), width = 9, height = 6)
```

```{r}
min_by_q %>% 
  ggplot() + geom_line(aes(x = year_q_date, y = log_n, col = ethnicity)) + gghighlight(ethnicity == "German") +
  labs(y = "log(1 + y)", x = "year") +  theme_minimal() + 
  scale_y_continuous(limits = c(0, NA), expand = c(0,0)) +
  theme(axis.line = element_line(size = 0.75))

ggsave(here::here("plots/arrests_by_ethnicity_quart_highlight.pdf"))

min_by_q %>% 
  count(ethnicity) %>% 
  write_xlsx("data/ethnicity_info.xlsx")

```

## Monthly data

```{r}
min_by_month %>% 
  ggplot(aes(x = date, y = log_n)) + geom_line() + facet_wrap(~ethnicity) +
  labs(y = "log(1 + y)", x = "year") + theme_bw()

ggsave(here("plots/arrests_by_ethnicity_quart.pdf"), width = 9, height = 6)
```

