---
title: "Time window"
author: "Martin Kosík"
date: "8 dubna 2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(estimatr)
library(clubSandwich)
```


```{r}
fmla_window <- as.formula(paste("log_n ~ german:hostility + german:pact + german:war +  german:post_war +
                                as.factor(YEAR) + ethnicity + ethnicity:YEAR + ethnicity:YEAR_sq"))

fmla_window_pre_treat_pred_full_imp_date <-
                    as.formula("log_n_pred_full_imp_date ~ german:pre_treatment + german:hostility + german:pact +
                                    german:war +  german:post_war +  as.factor(YEAR) + 
                                    ethnicity + ethnicity:YEAR + ethnicity:YEAR_sq")

fmla_window_pre_treat_pred_full_imp_date_lin_trends <-
                    as.formula("log_n_pred_full_imp_date ~ german:pre_treatment + german:hostility + german:pact +
                                    german:war +  german:post_war +  as.factor(YEAR) + 
                                    ethnicity + ethnicity:YEAR")

fmla_window_pre_treat_pred_full_imp_date_no_trends <-
                    as.formula("log_n_pred_full_imp_date ~ german:pre_treatment + german:hostility + german:pact +
                                    german:war +  german:post_war +  as.factor(YEAR) + 
                                    ethnicity")

```


```{r}
fmla_window_pre_treat_pred_full_imp_date_geopol <-
                    as.formula(paste0("log_n_pred_full_imp_date ~ german:pre_treatment+german:hostility +german:pact +
                                    german:war +  german:post_war +  as.factor(YEAR) + 
                                    ethnicity + ethnicity:YEAR + ethnicity:YEAR_sq +", 
                                    paste0(geopol_vars, collapse = " + ")))

fmla_window_pre_treat_pred_full_imp_date_lin_trends_geopol <-
                    as.formula(paste0("log_n_pred_full_imp_date ~ german:pre_treatment+german:hostility +german:pact +
                                    german:war +  german:post_war +  as.factor(YEAR) + 
                                    ethnicity + ethnicity:YEAR +", 
                                    paste0(geopol_vars, collapse = " + ")))



fmla_window_pre_treat_pred_full_imp_date_no_trends_geopol <-
                    as.formula(paste0("log_n_pred_full_imp_date ~ german:pre_treatment+german:hostility +german:pact +
                                    german:war +  german:post_war +  as.factor(YEAR) + 
                                    ethnicity +", 
                                    paste0(geopol_vars, collapse = " + ")))

```


```{r}
diff_model_window_pre_treat <- lm(fmla_window_pre_treat, data = min_by_year)
```


```{r}
formula = fmla_window_pre_treat_pred_full_imp_date
data = min_by_year
level = 0.95
vcov = "CR2"

  model <- lm(formula,  data = data)
  model %>% 
  conf_int(vcov = vcov,  level = level,
          cluster = data$ethnicity,  test = "Satterthwaite") %>% 
  as_tibble(rownames = "term") %>% 
  filter(str_detect(term, "german:")) %>% 
  mutate(nice_labs = str_replace(term,"german:","") %>% 
           fct_relevel("pre_treatment", "hostility", "pact", "war", "post_war")) %>% 
  rename(conf.low = CI_L, conf.high = CI_U, estimate = beta) %>% 
  ggplot(mapping = aes(x = nice_labs, y = estimate, ymin = conf.low, ymax = conf.high, group = 1))+ 
  geom_pointrange()+  geom_hline(yintercept= 0) + theme_minimal() +
  theme(axis.line = element_line(size = 1), 
        panel.grid.major.x = element_blank(), panel.grid.minor.x = element_blank(), 
        text = element_text(size=14)) + 
  labs(x = element_blank(),
       #caption = "error bars show 95% confidence intervals \n 
        #            SE are based on the cluster-robust estimator by Pustejovsky and Tipton (2018)",
       y = "Coefficient"
      # title = "Interactions of German ethnicity with specified time window dummy"
       ) + 
  scale_x_discrete(labels = c("Pre-tretment \n (1930 to 1932)",
                              'Hostility without war \n (1933 to 1939)',
                              'Pact \n (1940)', 'War \n (1941 to 1944)',
                              "Post-war \n (from 1945)"))

ggsave(here::here("plots/effects/ethnicity_imputation/annual/time_window_pre_treatment_date_imp.pdf"))
```



```{r}
formula = fmla_window_pre_treat_pred_full_imp_date
data = min_by_year
level = 0.95
vcov = "CR2"
fit_robust_model <- function(formula = fmla_window_pre_treat_pred_full_imp_date, 
                             data = min_by_year, level = 0.95, vcov = "CR2", estimatr = 1){
  if (estimatr != 1){
  model <- lm(formula,  data = data)
  model %>% 
  conf_int(vcov = vcov,  level = level,
          cluster = data$ethnicity,  test = "Satterthwaite") %>% 
  as_tibble(rownames = "term") %>% 
  filter(str_detect(term, "german:")) %>% 
 # mutate(nice_labs = str_replace(term,"german:","") %>% 
 #          fct_relevel("pre_treatment", "hostility", "pact", "war", "post_war")) %>% 
  rename(conf.low = CI_L, conf.high = CI_U, estimate = beta)
  }
  else {
    model_robust <- lm_robust(formula = formula, data = data, clusters = ethnicity, se_type = vcov,
                                ci = TRUE, alpha = 1 - level)
    model_robust %>% 
      estimatr::tidy(model_robust) %>% 
      filter(str_detect(term, "german:")) %>% 
      dplyr::select(term, estimate, SE = std.error,  conf.low, conf.high) %>% 
      as_tibble()
      
      
  }
  }
```

```{r}
fit_robust_model(fmla_window_pre_treat_pred_full_imp_date_lin_trends)

trends_formulas <-  c(fmla_window_pre_treat_pred_full_imp_date, fmla_window_pre_treat_pred_full_imp_date_lin_trends,
  fmla_window_pre_treat_pred_full_imp_date_no_trends)

map(trends_formulas, ~ fit_robust_model(formula = ., estimatr = 0)) %>% 
  bind_rows(.id = "id") %>% 
  mutate(nice_labs = str_replace(term,"german:","") %>% 
           fct_relevel("pre_treatment", "hostility", "pact", "war", "post_war")) %>% 
  mutate(trends = recode_factor(id, "1" = "Quadratic", "2" = "Linear", "3" = "None")) %>% 
  ggplot(mapping = aes(x = nice_labs, y = estimate, ymin = conf.low, ymax = conf.high, group = 1, col = trends))+ 
  geom_pointrange(position = position_dodge2(width = 0.4))+  geom_hline(yintercept= 0) + theme_minimal() +
  theme(axis.line = element_line(size = 1), 
        panel.grid.major.x = element_blank(), panel.grid.minor.x = element_blank(), 
        text = element_text(size=14)) + 
  labs(x = element_blank(),
       #caption = "error bars show 95% confidence intervals \n 
        #            SE are based on the cluster-robust estimator by Pustejovsky and Tipton (2018)",
       y = "Coefficient", col = "Ethnicity-specific \n time trends"
      # title = "Interactions of German ethnicity with specified time window dummy"
       ) + 
  scale_x_discrete(labels = c("Pre-tretment \n (1930 to 1932)",
                              'Hostility without war \n (1933 to 1939)',
                              'Pact \n (1940)', 'War \n (1941 to 1945)',
                              "Post-war \n (from 1945)"))

```



```{r}

summary(lm(fmla_pred_full_imp_date, min_by_year))
summary(lm(fmla_pred_full_imp_date_lin_trends, min_by_year))


trends_formulas_full_years <-  c(fmla_pred_full_imp_date, fmla_pred_full_imp_date_lin_trends,
                                 fmla_pred_full_imp_date_no_trends)

trends_formulas_full_years_geopol <- c(fmla_pred_full_imp_date_geopol, fmla_pred_full_imp_date_lin_trends_geopol,
                                       fmla_pred_full_imp_date_no_trends_geopol)


## Position dodge
map(trends_formulas_full_years_geopol, ~ fit_robust_model(formula = ., vcov = "CR2", estimatr = 0)) %>% 
  bind_rows(.id = "id") %>% 
  mutate(nice_labs = str_replace(term,"german:year_","")
   #      ,nice_labs = ifelse(as.numeric(nice_labs) == max(as.numeric(nice_labs)), str_c(nice_labs, "+"), nice_labs)
         ) %>% 
  mutate(trends = recode_factor(id, "1" = "Quadratic", "2" = "Linear", "3" = "None")) %>% 
  ggplot( aes(x = nice_labs, y = estimate, ymin = conf.low, ymax = conf.high, group = 1, col = trends))+ 
  geom_pointrange(position = position_dodge2(width = 0.45))+  geom_hline(yintercept= 0) + theme_minimal() + 
  theme(axis.line = element_line(size = 1), 
        panel.grid.major.x = element_blank(), panel.grid.minor.x = element_blank(), 
        text = element_text(size=14),
        legend.position = "bottom", 
        axis.text.x = element_text(angle = 60, hjust = 1)) +
  labs(x = "Year", 
        #caption = "error bars show 95% confidence intervals \n 
         #                      SE are based on the cluster-robust estimator by Pustejovsky and Tipton (2018)", 
       y = "Coefficient", col = "Ethnicity-specific time trends")

ggsave(here::here("plots/effects/robustness_checks/trends_comp_pred_full_imp_date_cr2.pdf"))
```


```{r}
geopol_vars <- str_subset(names(min_by_year), "geopol")

fmla_pred_imp_date_no_trends_geopol <- as.formula(paste("log_n_pred_imp_date ~ ", 
                         paste0("german:","year_", years, collapse = " + "),  "+ as.factor(YEAR) +
                         ethnicity+ ",  paste0(geopol_vars, collapse = " + ")))

fmla_pred_full_imp_date_no_trends_geopol <- as.formula(paste("log_n_pred_full_imp_date ~ ", 
                         paste0("german:","year_", years, collapse = " + "),  "+ as.factor(YEAR) +
                         ethnicity+ ",  paste0(geopol_vars, collapse = " + ")))

fmla_pars_pred_imp_date_no_trends_geopol <- as.formula(paste("log_n_pred_pars_imp_date ~ ", 
                         paste0("german:","year_", years, collapse = " + "),  "+ as.factor(YEAR) +
                         ethnicity+ ",  paste0(geopol_vars, collapse = " + ")))
```

```{r}
fmla_pred_imp_date <- as.formula(paste("log_n_pred_imp_date ~ ", 
                         paste0("german:","year_", years, collapse = " + "),  "+ as.factor(YEAR) +
                         ethnicity + ethnicity: YEAR+ ethnicity: YEAR_sq"))
fmla_pred_full_imp_date <- as.formula(paste("log_n_pred_full_imp_date ~ ", 
                         paste0("german:","year_", years, collapse = " + "),  "+ as.factor(YEAR) +
                         ethnicity + ethnicity: YEAR+ ethnicity: YEAR_sq"))

fmla_pars_pred_imp_date <- as.formula(paste("log_n_pred_pars_imp_date ~ ", 
                         paste0("german:","year_", years, collapse = " + "),  "+ as.factor(YEAR) +
                         ethnicity + ethnicity: YEAR+ ethnicity: YEAR_sq"))

```


```{r}
pred_adj_formulas_full_years <-  c(fmla_pred_full_imp_date, fmla_pars_pred_imp_date,
                                 fmla_pred_imp_date)

pred_adj_formulas_full_years_geopol <- c(fmla_pred_full_imp_date_no_trends_geopol,
                                       fmla_pars_pred_imp_date_no_trends_geopol,
                                       fmla_pred_imp_date_no_trends_geopol)

## Position dodge
map(pred_adj_formulas_full_years_geopol, ~ fit_robust_model(formula = ., vcov = "CR2", estimatr = 0)) %>% 
  bind_rows(.id = "id") %>% 
  mutate(nice_labs = str_replace(term,"german:year_","")
         #,nice_labs = ifelse(as.numeric(nice_labs) == max(as.numeric(nice_labs)), str_c(nice_labs, "+"), nice_labs)
         ) %>% 
  mutate(trends = recode_factor(id, "1" = "Full matrix", "2" = "Parsimonious", "3" = "None")) %>% 
  ggplot( aes(x = nice_labs, y = estimate, ymin = conf.low, ymax = conf.high, group = 1, col = trends))+ 
  geom_pointrange(position = position_dodge2(width = 0.45))+  geom_hline(yintercept= 0) + theme_minimal() + 
  theme(axis.line = element_line(size = 1), 
        panel.grid.major.x = element_blank(), panel.grid.minor.x = element_blank(), 
        text = element_text(size=14),
        legend.position = "bottom", 
        axis.text.x = element_text(angle = 60, hjust = 1)) +
  labs(x = "Year", 
        #caption = "error bars show 95% confidence intervals \n 
         #                      SE are based on the cluster-robust estimator by Pustejovsky and Tipton (2018)", 
       y = "Coefficient", col = "Ethnicity imputaiton adjustment")

ggsave(here::here("plots/effects/robustness_checks/pred_adj_comp_pred_full_imp_date_cr2.pdf"))

```


```{r}
min_by_year %>% 
  mutate(number_pred_imp_date = label_imp_date + pred_adj_full_scaled_imp_date) %>% 
  dplyr::select(ethnicity, YEAR, number_pred_imp_date) %>% 
  View()

min_by_year %>% 
  count(ethnicity)

```

