---
title: "until pact version"
author: "Martin Kosík"
date: "28 února 2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
min_by_q <- min_by_q  %>% 
  filter(year_q_date < ymd(19390823))
```

## MSCMT implementation
### Quarterly observations 
```{r}
data_prep_mscmt <- listFromLong(as.data.frame(min_by_q), unit.variable = "ethnicity_id", 
                                time.variable="year_str_rep", unit.names.variable="ethnicity")

```

```{r}
treatment.identifier <- "German"
controls.identifier  <- setdiff(colnames(data_prep_mscmt[[1]]),
                                 treatment.identifier)
times.dep  <- cbind("log_n"                 = c("1921Q1","1933Q1"))
times.pred <- cbind("pop_total"             = c("1921Q2","1932Q1"),
                    "clad_sim"              = c("1921Q2","1932Q1"),
                    "urb_rate"              = c("1921Q2","1932Q1"))

#agg.fns <- rep("mean", ncol(times.pred))                       
agg.fns <- rep("id", ncol(times.pred))
```

```{r}
sc_results <- mscmt(data_prep_mscmt, treatment.identifier, controls.identifier, times.dep, times.pred, agg.fns, seed=2019, single.v=TRUE)
improveSynth(data_prep, synth.out)
```

```{r}
library(timetk)
timetk::tk_tbl(sc_results$combined$log_n) %>% 
  mutate(date = as_date(index)) %>% 
  gather("type", "log_n", treated, synth, -date) %>% 
  mutate(type = fct_recode(type, "Synthetic" = "synth", "Actual" = "treated") %>% 
           fct_relevel("Actual")) %>% 
  ggplot(aes(x = date, y = log_n, col = type)) + theme_minimal() +
  theme(axis.line = element_line(size = 1), 
        #panel.grid.major.x = element_blank(), panel.grid.minor.x = element_blank(), 
        text = element_text(size=12)) + 
  annotate("rect", fill = "grey", alpha = 0.4, 
        xmin = as_date("1921-01-01"), xmax = as_date("1933-01-01"),
        ymin = -Inf, ymax = Inf) + 
   geom_line(size = 1) +
  scale_x_date(date_minor_breaks = "1 year", date_breaks = "2 year", date_labels = "%Y", 
               limits = c(as_date("1921-01-01"), NA)) +
  labs(x = element_blank(), y = "log(1 + arrests)", col = "German arrests") 
ggsave(here::here("plots/synthetic_control/until_pact/comparison_plot.pdf"))

```

```{r}
tk_tbl(sc_placebo$placebo$log_n$gaps) %>% 
  mutate(date = as_date(index)) %>% 
  gather("ethnicity", "log_n", -c(date, index)) %>% 
  ggplot(aes(date, log_n, col = ethnicity)) + geom_line(size = 1)  + gghighlight(ethnicity == "German") +
  theme_minimal() +
  theme(axis.line = element_line(size = 1), 
        #panel.grid.major.x = element_blank(), panel.grid.minor.x = element_blank(), 
        text = element_text(size=12)) + 
  labs(x = element_blank(), y = "gaps in log(1 + arrests)") +
  geom_vline(xintercept= ymd(19330301), col = "black", linetype = "dashed", size = 1)+
    scale_x_date(date_minor_breaks = "1 year", date_breaks = "2 year", date_labels = "%Y") 

ggsave(here("plots/synthetic_control/until_pact/placebo_highlight_all.pdf"))

```


```{r}
rmspe_placebo <- sc_placebo[-length(sc_placebo)] %>% 
  map("rmspe") %>% 
  map_dbl(1) 

rmspe_placebo_tibble <- tibble(ethnicity = names(rmspe_placebo), rmspe = rmspe_placebo) %>% 
  mutate(mspe = rmspe^2) %>% 
  mutate( mspe_german = mspe[ethnicity == "German"],
         mspe_5times_higher = ifelse(5 * mspe_german < mspe, 1, 0), 
         mspe_20times = ifelse(20 * mspe_german < mspe, 1, 0))

tk_tbl(sc_placebo$placebo$log_n$gaps) %>% 
  mutate(date = as_date(index)) %>% 
  gather("ethnicity", "log_n", -c(date, index)) %>% 
  left_join(rmspe_placebo_tibble, by = "ethnicity") %>% 
  filter(!mspe_5times_higher) %>% 
  ggplot(aes(date, log_n, col = ethnicity)) + geom_line(size = 1)  + gghighlight(ethnicity == "German") +
  theme_minimal() +
  theme(axis.line = element_line(size = 1), 
        #panel.grid.major.x = element_blank(), panel.grid.minor.x = element_blank(), 
        text = element_text(size=12)) + 
  labs(x = element_blank(), y = "gaps in log(1 + arrests)") +
  geom_vline(xintercept= ymd(19330301), col = "black", linetype = "dashed", size = 1)+
    scale_x_date(date_minor_breaks = "2 year", date_breaks = "4 year", date_labels = "%Y") 

ggsave(here("plots/synthetic_control/until_pact/placebo_highlight_mspe_5_lower.pdf"))

```

# Difference-in-differences
```{r}
min_by_month <- read_csv(here::here("data/cleaned_min_arrests_by_month.csv"))


min_by_q <-  min_by_month %>% 
  mutate(year_q = quarter(date, with_year = T),
         year_q_date = floor_date(date, unit = "quarter")) %>% 
  group_by(year_q, year_q_date, ethnicity, german) %>% 
  summarize(n = sum(n)) %>% 
  ungroup() %>% 
  mutate(log_n = log(n + 1)) %>% 
  group_by(ethnicity) %>% 
  mutate(t = row_number()) %>% 
  ungroup() %>% 
  mutate(pre_treatment = ifelse(year_q_date >= "1928-01-01" & year_q_date <= "1933-01-01", 1, 0),
         hostility = ifelse(year_q_date >= "1933-03-23" & year_q_date <= "1939-08-23", 1, 0), 
         pact = ifelse(year_q_date > "1939-08-23" & year_q_date < "1941-06-22", 1, 0), 
         war = ifelse(year_q_date >= "1941-06-22" & year_q_date < "1945-05-08", 1, 0),
         post_war = ifelse(year_q_date >= "1945-05-08", 1, 0), 
         ethnicity = as.factor(ethnicity)) 
```

```{r}
year_quarters <- crossing(year = 1930:1939, quarter = 1:4) %>% 
  mutate(yq = str_c(year, quarter, sep = ".")) %>% 
  pull(yq)

```

```{r}
diff_model_robust %>% 
  estimatr::tidy(conf.int = TRUE) %>% 
 # broom::tidy(conf.int = TRUE) %>% 
  filter(str_detect(term, "german:")) %>% 
  mutate(nice_labs = str_replace(term,"german:year_","") %>% 
           str_replace("\\.", " Q") %>% 
           as.yearqtr() %>% 
           as.Date()) %>% 
  ggplot(mapping = aes(x = nice_labs, y = estimate, ymin = conf.low, ymax = conf.high, group = 1))+ 
  geom_vline(xintercept= ymd(c(19330323, 19390823, 19410622)), col = "red", linetype = "dashed") +
  geom_pointrange()+  geom_hline(yintercept= 0) + theme_bw() + 
  scale_x_date(date_minor_breaks = "1 year", date_breaks = "2 year", date_labels = "%Y")+
  labs(x = "Year", y = "Coefficient",
       caption = "error bars show 95% confidence intervals \n 
                    SE are based on the small-sample cluster-robust estimator by Pustejovsky and Tipton (2018)"
       #title = "Estimates on interactions of german*year-quarter"
       )

ggsave(here::here("plots/effects/quarterly/until_pact/pointrange_robust.pdf"))


```

